//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBootstrapDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int E_ID { get; set; }
        public string E_FullName { get; set; }
        public Nullable<int> E_Department { get; set; }
        public Nullable<int> E_Position { get; set; }
        public string E_Username { get; set; }
        public Nullable<bool> E_Active { get; set; }
    }
}
