//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBootstrapDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int H_ID { get; set; }
        public Nullable<int> To_ID { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> ActiveID { get; set; }
        public string Remark { get; set; }
    }
}
