//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBootstrapDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Inventory
    {
        public int ID { get; set; }
        public string CodeNo { get; set; }
        public Nullable<int> GenNo { get; set; }
        public Nullable<int> Maincategory { get; set; }
        public Nullable<int> Category { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Purchaser { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        public Nullable<System.DateTime> UseDate { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Currency { get; set; }
        [DataType(DataType.MultilineText)]
        public string Remark { get; set; }
        public Nullable<decimal> ReturnSellAmount { get; set; }
        public Nullable<int> ReturnCurrency { get; set; }
    }
}
