//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCBootstrapDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public int Pos_ID { get; set; }
        public string Pos_Name { get; set; }
        public Nullable<int> Pos_SortOrder { get; set; }
    }
}
